// <auto-generated />
using System;
using LuxFactaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LuxFactaAPI.Migrations
{
    [DbContext(typeof(LuxFactaAPIContext))]
    [Migration("20200903230916_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LuxFactaAPI.Models.Poll", b =>
                {
                    b.Property<int>("Poll_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Poll_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Poll_id");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("LuxFactaAPI.Models.PollOption", b =>
                {
                    b.Property<int>("Option_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Option_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<int?>("Poll_id")
                        .HasColumnType("int");

                    b.HasKey("Option_id");

                    b.HasIndex("Poll_id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("LuxFactaAPI.Models.Vote", b =>
                {
                    b.Property<int>("Vote_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Option_Id")
                        .HasColumnType("int");

                    b.Property<int>("Poll_Id")
                        .HasColumnType("int");

                    b.HasKey("Vote_Id");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("LuxFactaAPI.Models.PollOption", b =>
                {
                    b.HasOne("LuxFactaAPI.Models.Poll", null)
                        .WithMany("Options")
                        .HasForeignKey("Poll_id");
                });
#pragma warning restore 612, 618
        }
    }
}
